name = "FastGraphletTransform"
uuid = "8757296b-2078-477d-a41d-7d2812277c39"
authors = ["Jason Barmparesos <jason@jasonb.dev>, Dimitris Floros <flojim4@gmail.com>, and contributors"]
version = "1.1.0"

[deps]
FGlT_jll = "34b0a953-27c5-5560-82f5-8ee8a9e462bb"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
FGlT_jll = "1"
Graphs = "1"
julia = "1.6"

[extras]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Match"]
